
import React, { useState, useEffect } from 'react';
import { Icons } from './Icons';
import { generateSEOContent } from '../services/geminiService';

export const AIContentGenerator: React.FC = () => {
  const [content, setContent] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    // Simulate "Fresh" content generation on mount to boost SEO relevance perception
    const fetchDailyInsight = async () => {
      setLoading(true);
      const insight = await generateSEOContent("Current UK Business Energy Market Trends and Tips for Saving Money");
      setContent(insight);
      setLoading(false);
    };
    
    fetchDailyInsight();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <section className="py-16 bg-watt-light">
      <div className="container mx-auto px-4">
        <div className="flex items-center gap-3 mb-8">
            <div className="p-2 bg-gradient-to-r from-watt-dark to-gray-800 rounded-lg text-white">
                <Icons.Zap size={24} />
            </div>
            <h2 className="text-3xl font-bold text-watt-dark">Daily Energy Market Insights</h2>
        </div>
        
        <div className="bg-white p-8 rounded-2xl shadow-xl border border-gray-100 flex flex-col lg:flex-row gap-8">
           <div className="lg:w-1/3">
              <h3 className="text-xl font-bold text-gray-800 mb-4">Why Read This?</h3>
              <p className="text-gray-600 mb-6">
                Our AI-powered analysis engine monitors the UK wholesale market 24/7 to bring you the latest advice on when to fix your contracts.
              </p>
              <div className="p-4 bg-gray-50 rounded-lg border border-gray-100">
                <p className="text-sm text-gray-800 font-semibold flex items-center gap-2">
                    <Icons.TrendingUp size={16} />
                    Market Volatility: <span className="text-red-500">High</span>
                </p>
              </div>
           </div>

           <div className="lg:w-2/3 relative min-h-[200px]">
              {loading ? (
                <div className="absolute inset-0 flex items-center justify-center bg-white/80 z-10">
                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-watt-dark"></div>
                </div>
              ) : (
                <div className="prose prose-gray max-w-none">
                    <div dangerouslySetInnerHTML={{ __html: content }} />
                    <p className="text-xs text-gray-400 mt-4 italic">Generated by Watt Utilities AI Intelligence Engine</p>
                </div>
              )}
           </div>
        </div>
      </div>
    </section>
  );
};